#!/bin/sh

# Copyright (C) 2005 - 2008  Eric Van Dewoestine
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Eclipse requires access to the user's display
DISPLAY=":0.0"

# the user to run as.
ECLIM_USER="ervandew"

# jdk home
JAVA_HOME="/opt/java"

# eclipse installation dir.
ECLIPSE_HOME="/usr/local/java/eclipse"

# eclim plugin dir.
ECLIM_HOME="$ECLIPSE_HOME/plugins/org.eclim_${eclim.version}"

case "$1" in
  start)
    echo "Starting eclimd"
    su $ECLIM_USER -c \
      "source /etc/profile && DISPLAY='$DISPLAY' JAVA_HOME='$JAVA_HOME' ECLIPSE_HOME='$ECLIPSE_HOME' '$ECLIM_HOME/bin/eclimd' start"
    echo
    ;;

  stop)
    echo "Stopping eclimd"
    su $ECLIM_USER -c \
      "source /etc/profile && JAVA_HOME='$JAVA_HOME' '$ECLIM_HOME/bin/eclim' -command shutdown"
    echo
    ;;

  restart)
    $0 stop
    $0 start
    ;;

  *)
    echo "Usage: eclimd {start|stop|restart}"
    exit 1
esac

exit $?
