#!/bin/sh

# Copyright (c) 2005 - 2006
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Author: Eric Van Dewoestine

# Eclipse requires access to the user's display
DISPLAY=":0.0"
# jdk home
JAVA_HOME="/opt/java"
# eclipse installation dir.
ECLIPSE_HOME="/usr/local/java/eclipse"
# eclim plugin dir.
ECLIM_HOME="$ECLIPSE_HOME/plugins/org.eclim_${eclim.version}"
# the user to run as.
ECLIM_USER="ervandew"

case "$1" in
  start)
    echo "Starting eclimd"
    su $ECLIM_USER -c \
      "source /etc/profile && DISPLAY='$DISPLAY' JAVA_HOME='$JAVA_HOME' ECLIPSE_HOME='$ECLIPSE_HOME' '$ECLIM_HOME/bin/eclimd' start"
    echo
    ;;

  stop)
    echo "Stopping eclimd"
    su $ECLIM_USER -c \
      "source /etc/profile && JAVA_HOME='$JAVA_HOME' '$ECLIM_HOME/bin/eclim' -command shutdown"
    echo
    ;;

  restart)
    $0 stop
    $0 start
    ;;

  *)
    echo "Usage: eclimd {start|stop|restart}"
    exit 1
esac

exit $?
