#!/bin/sh

# Copyright (C) 2005 - 2009  Eric Van Dewoestine
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

usage(){
  echo "Usage: eclim [-f eclimrc] -command <command> <command-args>"
  echo "    -f   specify the location of an eclimrc file other than the"
  echo "         default (~/.eclimrc). Must be the first option supplied."
}

FILEPATH="$0"
# handle symlink to eclim script
# readlink -f is easier, but not supported on mac or bsd
while [ -h "$FILEPATH" ] ; do
  PREV=$FILEPATH
  FILEPATH=`readlink "$FILEPATH"`
  if [ -z "$FILEPATH" -o "$FILEPATH" = "$PREV" ] ; then
    FILEPATH=$PREV
    break
  fi
done
CURPATH=`dirname "$FILEPATH"`

SED=`which sed 2> /dev/null`

ECLIMRC=$HOME/.eclimrc
if [ "$1" = "-f" ] ; then
  while getopts ":f:" opt ; do
    case "$opt" in
      f)
        ECLIMRC="$OPTARG"
        shift
        shift
        break
        ;;
      \?)
        continue
        ;;
      :)
        echo "missing argument for: -$OPTARG"
        exit 1
        ;;
    esac
  done
fi

# attempt to grab port number from .eclimrc file if available.
if [ -f "$ECLIMRC" -a -n "$SED" ] ; then
  ARGS=`sed -n -f "$CURPATH/eclim.sed" "$ECLIMRC"`
  if [ "$ARGS" != "" ] ; then
    NAILGUN_ARGS=$ARGS
  fi
fi

# allow nailgun port to be supplied on the command line like eclimd
# ex. eclim -Dnailgun.server.port=9092 -command ping
if [ -n "$SED" -a -n "$1" ] ; then
  ARG=`echo "$1" | sed '/^-Dnailgun.server.\(.*\)=/!d'`
  if [ -n "$ARG" ] ; then
    shift
    NAILGUN_ARGS=`
      echo $ARG | \
      sed 's/-Dnailgun.server.\(\w*\)\s*=\s*\(\w*\)\s*/ --nailgun-\1 \2/g'
    `
  fi
fi

if [ -z "$NAILGUN_ARGS" ] ; then
  NAILGUN_ARGS="--nailgun-port 9091"
fi

"$CURPATH/ng" $NAILGUN_ARGS org.eclim.command.Main "$@" 2>&1

# Weirdest thing that for the life of me I can't figure out.
# Sometimes when executed through vim, the exit status will be
# 227 even though no error occurred.  Trying to reproduce with
# manual system() or ! call, all work fine.
# So, here we just swallow the 227 error code.
EXIT_STATUS=$?
if [ $EXIT_STATUS -eq 227 ]; then
  exit 0
fi
exit $EXIT_STATUS
