#!/bin/sh

# Copyright (C) 2005 - 2010  Eric Van Dewoestine
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

usage(){
  echo "Usage: eclimd [-f eclimrc] [jvmarg ...]"
  echo "    -f   specify the location of an eclimrc file other than the"
  echo "         default (~/.eclimrc). Must be the first option supplied."
}

##
# Determines eclim's home directory and sets the ECLIM_HOME var to that path.
#
resolve_eclim_home(){
  FILEPATH="$0"

  # handle symlink to eclimd script
  # readlink -f is easier, but not supported on mac or bsd
  while [ -h "$FILEPATH" ] ; do
    PREV=$FILEPATH
    FILEPATH=`readlink "$FILEPATH"`
    if [ -z "$FILEPATH" -o "$FILEPATH" = "$PREV" ] ; then
      FILEPATH=$PREV
      break
    fi

    # handle relative symlinks (neither eclim build nor installer create these,
    # so must have been created by the user or 3rd party installer)
    if [ ! -f "$FILEPATH" ] ; then
      PREVDIR=`dirname "$PREV"`
      FILEPATH=$PREVDIR/$FILEPATH
    fi
  done

  CURPATH=`dirname "$FILEPATH"`
  ECLIM_HOME=`cd "$CURPATH/.." ; pwd`
}

##
# Determines the eclipse home path and the eclipse launcher jar and sets
# ECLIM_ECLIPSE_HOME and ECLIPSE_LAUNCHER to those results.
#
resolve_eclipse_launcher(){
  #${eclipse.home}
  if [ -z "$ECLIM_ECLIPSE_HOME" -o ! -d "$ECLIM_ECLIPSE_HOME" ]; then
    ECLIM_ECLIPSE_HOME=`cd "$ECLIM_HOME/../../"; pwd`
  fi

  ECLIPSE_LAUNCHER=`find "$ECLIM_ECLIPSE_HOME/plugins" -name 'org.eclipse.equinox.launcher_*.jar'`

  if [ ! -e "$ECLIPSE_LAUNCHER" ]; then
    echo "Unable to locate the eclipse launcher jar." 1>&2
    exit 1
  fi
}

##
# Builds a list of vm args to be passed to eclipse and sets ECLIM_VMARGS
# accordingly.
#
build_vmargs(){
  #ECLIMD_OPTS="-Djava.ext.dirs"
  ECLIM_VMARGS="$ECLIMD_OPTS"

  # attempt to grab properties from .eclimrc if available.
  SED=`which sed 2> /dev/null`
  if [ -f "$ECLIMRC" -a -n "$SED" ] ; then
    ECLIM_VMARGS="$ECLIM_VMARGS `
      sed -n -f \"$ECLIM_HOME/bin/eclimd.sed\" \"$ECLIMRC\"
    `"
  fi

  # for osx
  if [ `echo $OSTYPE | sed 's|[0-9][0-9]*\.[0-9][0-9]*||'` == "darwin" ] ; then
    ECLIM_VMARGS="$ECLIM_VMARGS -XstartOnFirstThread"
  fi
}

ECLIMRC=$HOME/.eclimrc

if [ "$1" = "-f" ] ; then
  while getopts ":f:" opt ; do
    case "$opt" in
      f)
        ECLIMRC="$OPTARG"
        shift
        shift
        break
        ;;
      \?)
        continue
        ;;
      :)
        echo "missing argument for: -$OPTARG"
        exit 1
        ;;
    esac
  done
fi

resolve_eclim_home
build_vmargs
resolve_eclipse_launcher

ECLIPSE_ARGS="-debug -clean -refresh -application org.eclim.application_headless"

if [ "$1" = "start" ]; then
  shift
  CLASSPATH="" java $ECLIM_VMARGS -jar "$ECLIPSE_LAUNCHER" $ECLIPSE_ARGS "$@" > /dev/null &
else
  echo "java $ECLIM_VMARGS -jar \"$ECLIPSE_LAUNCHER\" $ECLIPSE_ARGS $@"
  CLASSPATH="" java $ECLIM_VMARGS -jar "$ECLIPSE_LAUNCHER" $ECLIPSE_ARGS "$@"
fi
