#!/bin/sh

# Copyright (c) 2005 - 2006
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Author: Eric Van Dewoestine

if [ "$ECLIPSE_HOME" == '' ] ; then
  echo "ECLIPSE_HOME not set";
  exit 1;
fi

if [ ! -e "$ECLIPSE_HOME/eclipse" ] ; then
  echo "No eclipse executable found.  ECLIPSE_HOME may be invalid.";
  exit 1;
fi

ECLIM_HOME="$ECLIPSE_HOME/plugins/org.eclim_${eclim.version}"

$ECLIPSE_HOME/eclipse -debug -consolelog -nosplash -clean -refresh -application org.eclim.application \
  -vmargs -Declim.home="$ECLIM_HOME"
