#!/bin/sh

# Copyright (C) 2005 - 2008  Eric Van Dewoestine
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

CURPATH=`dirname "$0"`
SED=`which sed 2> /dev/null`
NAILGUN_ARGS="--nailgun-port 9091"

# attempt to grab port number from .eclimrc file if available.
if [ -f "$HOME/.eclimrc" -a -n "$SED" ] ; then
  ARGS=`sed -n -f "$CURPATH/eclim.sed" $HOME/.eclimrc`
  if [ "$ARGS" != "" ] ; then
    NAILGUN_ARGS=$ARGS
  fi
fi

"$CURPATH/ng" $NAILGUN_ARGS org.eclim.command.Main \
  "-Dvim.files=${vim.files}" "$@" 2>&1

# Weirdest thing that for the life of me I can't figure out.
# Sometimes when executed through vim, the exit status will be
# 227 even though no error occurred.  Trying to reproduce with
# manual system() or ! call, all work fine.
# So, here we just swallow the 227 error code.
EXIT_STATUS=$?
if [ $EXIT_STATUS -eq 227 ]; then
  exit 0
fi
exit $EXIT_STATUS
